version: "3.8"

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    volumes:
      - ./mysite/:/usr/src/mysite/
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_ENGINE: ${DB_ENGINE}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    depends_on:
      database:
        condition: service_started

  database:
    image: postgres:13.0-alpine
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${INT_PORT}:${DB_PORT}
    restart: always
    container_name: database
